import type { StorefrontProduct } from '../types';

/** Legacy demo SKUs — prefer catalog-driven inventory via getCatalogSummaries(). */
export const MOCK_INVENTORY: StorefrontProduct[] = [
  {
    id: 'ghk-cu-50mg',
    slug: 'ghk-cu',
    name: 'GHK-Cu',
    tag: '50mg',
    price: 49.0,
    stock: 150,
    desc: 'Investigated in vitro for collagen and elastin synthesis in dermal fibroblast assays. For laboratory research purposes only.',
    purity: '>99.2%',
    category: 'Dermal & Connective Tissue Research',
  },
  {
    id: 'bpc-157-5mg',
    slug: 'bpc-157',
    name: 'BPC-157',
    tag: '5mg',
    price: 49.0,
    stock: 85,
    desc: 'Body Protection Compound 157. Studied in connective tissue and ECM remodeling cell culture models. For laboratory research purposes only.',
    purity: '>99.5%',
    category: 'Connective Tissue Research',
  },
  {
    id: 'cjc-dac-2mg',
    slug: 'cjc-1295-dac',
    name: 'CJC-1295 w/ DAC',
    tag: '2mg',
    price: 45.0,
    stock: 40,
    desc: 'GHRH analogue for pituitary cell-line receptor kinetics studies. For laboratory research purposes only.',
    purity: '>99.1%',
    category: 'Somatotropic Axis Research',
  },
  {
    id: 'semaglutide-2mg',
    slug: 'semaglutide',
    name: 'Semaglutide',
    tag: '2mg',
    price: 110.0,
    stock: 0,
    desc: 'GLP-1 receptor agonist studied in incretin signaling cell-based assays. For laboratory research purposes only.',
    purity: '>99.8%',
    category: 'Incretin Receptor Research',
  },
  {
    id: 'tb-500-5mg',
    slug: 'tb-500',
    name: 'TB-500',
    tag: '5mg',
    price: 55.0,
    stock: 120,
    desc: 'Synthetic fraction of Thymosin Beta-4 for ECM remodeling assays. For laboratory research purposes only.',
    purity: '>98.9%',
    category: 'Connective Tissue Research',
  },
  {
    id: 'mots-c-10mg',
    slug: 'mots-c',
    name: 'MOTS-C',
    tag: '10mg',
    price: 65.0,
    stock: 30,
    desc: 'Mitochondrial-derived peptide studied in myocyte cell-line and energy metabolism assays. For laboratory research purposes only.',
    purity: '>99.0%',
    category: 'Cellular Energy Research',
  },
];
