'use client';

import { useMemo, useState } from 'react';
import { Badge } from '../../../components/ui/Badge';
import { Button } from '../../../components/ui/Button';
import type {
  ClinicEncounter,
  ClinicEncounterTranscript,
  EncounterLabOrderInput,
  StructuredClinicalNote,
} from '../../../lib/schemas/clinicEncounters';
import {
  finalizeEncounter,
  saveEncounterSoapDraft,
} from '../actions/encounterActions';

type SoapNoteEditorProps = {
  encounter: ClinicEncounter;
  transcript: ClinicEncounterTranscript;
  providerDisplayName: string;
  onFinalized?: () => void;
  onDraftSaved?: () => void;
};

type SoapField = 'summary' | 'subjective' | 'objective' | 'assessment' | 'plan';

const SOAP_FIELDS: { key: SoapField; label: string; hint: string }[] = [
  {
    key: 'summary',
    label: 'Summary',
    hint: 'Concise visit overview generated by ambient AI.',
  },
  {
    key: 'subjective',
    label: 'Subjective',
    hint: 'Patient-reported symptoms, history, and concerns.',
  },
  {
    key: 'objective',
    label: 'Objective',
    hint: 'Observations and measurable findings from the visit.',
  },
  {
    key: 'assessment',
    label: 'Assessment',
    hint: 'Clinical impression and diagnostic reasoning.',
  },
  {
    key: 'plan',
    label: 'Plan',
    hint: 'Treatment plan, follow-up, and orders.',
  },
];

function emptyNote(): StructuredClinicalNote {
  return {
    summary: '',
    subjective: '',
    objective: '',
    assessment: '',
    plan: '',
  };
}

function parseLabOrdersFromPlan(plan: string): EncounterLabOrderInput[] {
  const matches = plan.match(/(?:fullscript|lab)\s*(?:order|#)?\s*:?\s*([A-Za-z0-9_-]+)/gi) ?? [];
  const orders: EncounterLabOrderInput[] = [];

  for (const match of matches) {
    const orderId = match.replace(/.*?:?\s*([A-Za-z0-9_-]+)$/i, '$1');
    if (!orderId) continue;
    orders.push({
      orderId,
      title: `Lab order ${orderId}`,
      status: 'ordered',
    });
  }

  return orders;
}

export function SoapNoteEditor({
  encounter,
  transcript,
  providerDisplayName,
  onFinalized,
  onDraftSaved,
}: SoapNoteEditorProps) {
  const [note, setNote] = useState<StructuredClinicalNote>(() => ({
    ...emptyNote(),
    ...transcript.structuredNote,
  }));
  const [providerSignature, setProviderSignature] = useState(providerDisplayName);
  const [statusMessage, setStatusMessage] = useState<string | null>(null);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);
  const [isSavingDraft, setIsSavingDraft] = useState(false);
  const [isFinalizing, setIsFinalizing] = useState(false);

  const isReadOnly = encounter.status === 'finalized';
  const canEdit = encounter.status === 'review';

  const speakerPreview = useMemo(
    () => transcript.speakerSegments.slice(0, 12),
    [transcript.speakerSegments]
  );

  const updateField = (field: SoapField, value: string) => {
    setNote((current) => ({ ...current, [field]: value }));
  };

  const handleSaveDraft = async () => {
    if (!canEdit) return;

    setIsSavingDraft(true);
    setErrorMessage(null);
    setStatusMessage(null);

    const result = await saveEncounterSoapDraft({
      encounterId: encounter.id,
      structuredNote: note,
    });

    setIsSavingDraft(false);

    if (!result.ok) {
      setErrorMessage(result.error);
      return;
    }

    setStatusMessage('Draft note saved. Audio remains purged; transcript edits are retained.');
    onDraftSaved?.();
  };

  const handleFinalize = async () => {
    if (!canEdit) return;

    setIsFinalizing(true);
    setErrorMessage(null);
    setStatusMessage(null);

    const labOrders = parseLabOrdersFromPlan(note.plan ?? '');

    const result = await finalizeEncounter({
      encounterId: encounter.id,
      structuredNote: note,
      providerSignature,
      labOrders,
    });

    setIsFinalizing(false);

    if (!result.ok) {
      setErrorMessage(result.error);
      return;
    }

    const labMessage =
      result.data.labSyncCount > 0
        ? ` ${result.data.labSyncCount} lab order(s) dispatched to Fullscript sync.`
        : '';

    setStatusMessage(`Encounter finalized and archived.${labMessage}`);
    onFinalized?.();
  };

  return (
    <section className="rounded-sm border border-white/[0.06] bg-surface/20 overflow-hidden">
      <div className="border-b border-white/[0.06] px-5 py-3 flex flex-wrap items-center justify-between gap-3">
        <div>
          <h2 className="text-[10px] tracking-caps uppercase text-muted">SOAP Note Review</h2>
          <p className="mt-1 text-xs text-secondary font-light">
            Review AI-generated documentation before sign-off. Raw audio is not retained.
          </p>
        </div>
        <Badge variant={isReadOnly ? 'success' : 'neutral'}>
          {isReadOnly ? 'Finalized' : 'Awaiting Sign-Off'}
        </Badge>
      </div>

      <div className="grid gap-0 lg:grid-cols-2">
        <div className="border-b lg:border-b-0 lg:border-r border-white/[0.06] p-5 space-y-4">
          <div>
            <p className="text-[10px] tracking-caps uppercase text-muted">AI Transcript</p>
            <p className="mt-2 text-xs text-secondary font-light">
              Model {transcript.modelId ?? 'aws.healthscribe'}
              {transcript.modelVersion ? ` · ${transcript.modelVersion}` : ''}
            </p>
          </div>

          <div className="max-h-[420px] overflow-y-auto space-y-3 pr-1">
            {speakerPreview.length > 0 ? (
              speakerPreview.map((segment, index) => (
                <article
                  key={`${segment.speakerLabel}-${segment.startMs}-${index}`}
                  className="rounded-sm border border-white/[0.06] bg-void/20 px-3 py-2"
                >
                  <p className="text-[10px] tracking-caps uppercase text-gold-light/80">
                    {segment.speakerLabel}
                  </p>
                  <p className="mt-1 text-sm text-primary font-light leading-relaxed">
                    {segment.text}
                  </p>
                </article>
              ))
            ) : (
              <p className="text-sm text-secondary font-light whitespace-pre-wrap">
                {transcript.transcriptText}
              </p>
            )}
          </div>
        </div>

        <div className="p-5 space-y-4">
          {SOAP_FIELDS.map((field) => (
            <label key={field.key} className="block space-y-2">
              <span className="text-[10px] tracking-caps uppercase text-muted">{field.label}</span>
              <span className="block text-xs text-secondary font-light">{field.hint}</span>
              <textarea
                value={note[field.key] ?? ''}
                onChange={(event) => updateField(field.key, event.target.value)}
                readOnly={!canEdit}
                rows={field.key === 'plan' ? 5 : 4}
                className="w-full rounded-sm border border-white/[0.08] bg-void/30 px-3 py-2 text-sm text-primary font-light placeholder:text-muted focus:outline-none focus:border-gold-light/40 disabled:opacity-70"
                placeholder={`Enter ${field.label.toLowerCase()}…`}
              />
            </label>
          ))}

          {canEdit ? (
            <label className="block space-y-2">
              <span className="text-[10px] tracking-caps uppercase text-muted">Provider Signature</span>
              <input
                type="text"
                value={providerSignature}
                onChange={(event) => setProviderSignature(event.target.value)}
                className="w-full rounded-sm border border-white/[0.08] bg-void/30 px-3 py-2 text-sm text-primary font-light focus:outline-none focus:border-gold-light/40"
              />
            </label>
          ) : null}

          {statusMessage ? (
            <div className="rounded-sm border border-green-500/30 bg-green-500/5 px-4 py-3 text-sm text-green-300">
              {statusMessage}
            </div>
          ) : null}

          {errorMessage ? (
            <div className="rounded-sm border border-red-500/30 bg-red-500/5 px-4 py-3 text-sm text-red-300">
              {errorMessage}
            </div>
          ) : null}

          {canEdit ? (
            <div className="flex flex-wrap items-center gap-4 pt-2">
              <Button
                type="button"
                variant="ghost"
                disabled={isSavingDraft || isFinalizing}
                onClick={() => void handleSaveDraft()}
              >
                {isSavingDraft ? 'Saving Draft…' : 'Save Draft'}
              </Button>
              <Button
                type="button"
                variant="primary"
                disabled={isSavingDraft || isFinalizing || providerSignature.trim().length < 2}
                onClick={() => void handleFinalize()}
              >
                {isFinalizing ? 'Finalizing…' : 'Finalize Encounter'}
              </Button>
            </div>
          ) : null}
        </div>
      </div>
    </section>
  );
}
