import type { SystemNode } from './types';

export const SYSTEM_MAP_ZONES = [
  { id: 'infrastructure' as const, label: 'Infrastructure & Code', x: 4, y: 2, width: 92, height: 14 },
  { id: 'customer-ux' as const, label: 'Customer UX', x: 2, y: 18, width: 22, height: 58 },
  { id: 'core-engine' as const, label: 'Core Engine', x: 26, y: 16, width: 40, height: 62 },
  { id: 'integrations' as const, label: 'Integrations & Ops', x: 68, y: 16, width: 30, height: 62 },
  { id: 'compliance-ops' as const, label: 'Compliance & Sales Command', x: 8, y: 82, width: 84, height: 14 },
];

export const SYSTEM_NODES: SystemNode[] = [
  {
    id: 'github',
    zone: 'infrastructure',
    kind: 'pipeline',
    label: 'GitHub Repository',
    graphLabel: 'GITHUB',
    graphLabelShort: 'GIT',
    x: 12,
    y: 9,
    size: 'sm',
    purpose:
      'Source of truth for the TPT Peptides monorepo. Every push to main triggers Vercel production builds.',
    inputs: ['Developer commits', 'Pull request merges', 'CI workflow artifacts'],
    outputs: ['main branch webhook', 'Release tags', 'Git-connected deploy trigger'],
    automationStatus: 'Fully Automated',
    implementationStatus: 'live',
    infrastructure: {
      provider: 'GitHub',
      externalUrl: 'https://github.com/RobGDevelopment/tptpeptides',
    },
  },
  {
    id: 'vercel',
    zone: 'infrastructure',
    kind: 'pipeline',
    label: 'Vercel Edge Host',
    graphLabel: 'VERCEL',
    x: 28,
    y: 9,
    size: 'sm',
    purpose:
      'Hosts the Next.js 16 App Router runtime at the edge. Builds on Git push, serves API routes and webhooks.',
    inputs: ['GitHub push webhook', 'Environment variables', 'Build output'],
    outputs: ['Production URL', 'Serverless functions', 'Edge middleware'],
    automationStatus: 'Fully Automated',
    implementationStatus: 'live',
    infrastructure: {
      provider: 'Vercel',
      service: 'Edge Network',
      envVars: ['NEXT_PUBLIC_APP_URL', 'FIREBASE_*', 'STRIPE_*', 'RESEND_*'],
      externalUrl: 'https://medfit-pro.vercel.app',
    },
  },
  {
    id: 'firebase-auth',
    zone: 'infrastructure',
    kind: 'platform',
    label: 'Firebase Auth',
    graphLabel: 'FB AUTH',
    graphLabelShort: 'AUTH',
    x: 44,
    y: 9,
    size: 'sm',
    purpose: 'Identity provider for researchers, partners, and admin staff.',
    inputs: ['Email / password sign-in', 'ID token refresh', 'Partner invite links'],
    outputs: ['UID', 'ID token', 'Custom claims (role)'],
    automationStatus: 'Fully Automated',
    implementationStatus: 'live',
    infrastructure: { provider: 'Firebase', service: 'Authentication', envVars: ['NEXT_PUBLIC_FIREBASE_*'] },
  },
  {
    id: 'firestore',
    zone: 'infrastructure',
    kind: 'platform',
    label: 'Firestore Database',
    graphLabel: 'FIRESTORE',
    graphLabelShort: 'DB',
    x: 60,
    y: 9,
    size: 'sm',
    purpose: 'Primary operational datastore — products, orders, users, CMS, module flags, price lists.',
    inputs: ['Admin SDK writes', 'Client reads (rules-gated)', 'Webhook mutations'],
    outputs: ['Realtime documents', 'Transaction commits', 'Cached server reads'],
    automationStatus: 'Fully Automated',
    implementationStatus: 'live',
    infrastructure: {
      provider: 'Firebase',
      service: 'Firestore',
      envVars: ['FIREBASE_PROJECT_ID', 'FIREBASE_CLIENT_EMAIL', 'FIREBASE_PRIVATE_KEY'],
    },
  },
  {
    id: 'firebase-storage',
    zone: 'infrastructure',
    kind: 'platform',
    label: 'Firebase Storage',
    graphLabel: 'FB STORAGE',
    graphLabelShort: 'STORE',
    x: 76,
    y: 9,
    size: 'sm',
    purpose: 'Binary asset layer for W-9 uploads, institution documents, and batch COA PDFs.',
    inputs: ['Authenticated uploads', 'Admin SDK signed URLs', 'COA PDF binaries'],
    outputs: ['Storage object URLs', 'Download tokens', 'Compliance file archive'],
    automationStatus: 'Fully Automated',
    implementationStatus: 'live',
    infrastructure: {
      provider: 'Firebase',
      service: 'Cloud Storage',
      envVars: ['NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET'],
    },
  },
  {
    id: 'storefront-cms',
    zone: 'customer-ux',
    kind: 'platform',
    label: 'Storefront CMS',
    graphLabel: 'STOREFRONT CMS',
    graphLabelShort: 'CMS',
    x: 10,
    y: 24,
    purpose: 'Admin-driven homepage, hero merchandising, research articles, and protocol templates.',
    inputs: ['CMS admin saves', 'Firestore cms/* documents', 'Catalog seed exports'],
    outputs: ['Homepage layout', 'Research hub content', 'Category merchandising'],
    automationStatus: 'Hybrid',
    implementationStatus: 'live',
    adminHref: '/admin/storefront',
    adminLinkLabel: 'Open Storefront CMS',
  },
  {
    id: 'catalog',
    zone: 'customer-ux',
    kind: 'platform',
    label: 'Catalog / PIM',
    graphLabel: 'CATALOG',
    x: 10,
    y: 36,
    purpose: 'Product information management — SKU variants, research areas, stock visibility, tier pricing.',
    inputs: ['Firestore products collection', 'Price list overrides', 'CMS category rules'],
    outputs: ['Catalog grid', 'Product detail pages', 'Cart line SKU resolution'],
    automationStatus: 'Fully Automated',
    implementationStatus: 'live',
    adminHref: '/admin/products',
    adminLinkLabel: 'Open Products PIM',
    storefrontHref: '/catalog',
  },
  {
    id: 'cart',
    zone: 'customer-ux',
    kind: 'platform',
    label: 'Cart & Session',
    graphLabel: 'CART',
    x: 10,
    y: 48,
    purpose: 'Client-side cart persistence. Captures line items before checkout handoff.',
    inputs: ['PDP add-to-cart', 'Catalog SKU selection', 'Persisted local session'],
    outputs: ['Cart line payload', 'Subtotal snapshot', 'Checkout handoff'],
    automationStatus: 'Fully Automated',
    implementationStatus: 'live',
    storefrontHref: '/checkout',
  },
  {
    id: 'account-portal',
    zone: 'customer-ux',
    kind: 'platform',
    label: 'Client Account Portal',
    graphLabel: 'ACCOUNT',
    x: 10,
    y: 60,
    purpose: 'Order history, loyalty balance, institution verification status, and COA requests.',
    inputs: ['Session cookie', 'User profile document', 'Order history API'],
    outputs: ['Order timeline view', 'Verification CTA', 'Loyalty balance display'],
    automationStatus: 'Fully Automated',
    implementationStatus: 'live',
    storefrontHref: '/account',
  },
  {
    id: 'age-gate',
    zone: 'customer-ux',
    kind: 'platform',
    label: 'Age & RUO Gate',
    graphLabel: 'AGE GATE',
    graphLabelShort: 'GATE',
    x: 18,
    y: 30,
    size: 'sm',
    purpose: 'Mandatory 21+ attestation and RUO acknowledgment before catalog access.',
    inputs: ['First visit session', 'User agent fingerprint', 'Attestation click'],
    outputs: ['Age verified flag', 'Audit log entry', 'Catalog unlock signal'],
    automationStatus: 'Fully Automated',
    implementationStatus: 'live',
    adminHref: '/admin/audit',
    adminLinkLabel: 'Open Audit Logs',
  },
  {
    id: 'algolia-search',
    zone: 'customer-ux',
    kind: 'module',
    phase: '5',
    label: 'Algolia Search',
    graphLabel: 'ALGOLIA',
    x: 18,
    y: 42,
    size: 'sm',
    purpose: 'Typo-tolerant millisecond catalog discovery when enabled.',
    inputs: ['Catalog index sync', 'Search query string', 'Facet filters'],
    outputs: ['Ranked SKU results', 'Search analytics', 'Zero-result telemetry'],
    automationStatus: 'Fully Automated',
    implementationStatus: 'live',
    moduleKey: 'isAlgoliaSearchEnabled',
  },
  {
    id: 'ai-copilot',
    zone: 'customer-ux',
    kind: 'module',
    phase: '5',
    label: 'Research Co-Pilot',
    graphLabel: 'CO-PILOT',
    graphLabelShort: 'RAG',
    x: 18,
    y: 54,
    size: 'sm',
    purpose: 'RAG assistant on catalog.json — research context only, no medical advice.',
    inputs: ['catalog.json embeddings', 'User research query', 'Session context'],
    outputs: ['Grounded compound suggestions', 'Citation links', 'Safety disclaimers'],
    automationStatus: 'Fully Automated',
    implementationStatus: 'live',
    moduleKey: 'isAiCoPilotEnabled',
  },
  {
    id: 'interactive-3d',
    zone: 'customer-ux',
    kind: 'module',
    phase: '5',
    label: 'Interactive 3D',
    graphLabel: '3D UX',
    x: 18,
    y: 66,
    size: 'sm',
    purpose: 'WebGL molecular visuals and dynamic SVG vial renders for product storytelling.',
    inputs: ['Product molecular metadata', 'WebGL asset bundle', 'Viewport interaction'],
    outputs: ['3D molecule render', 'Vial animation state', 'Engagement telemetry'],
    automationStatus: 'Fully Automated',
    implementationStatus: 'live',
    moduleKey: 'isInteractive3dEnabled',
  },
  {
    id: 'abandoned-cart',
    zone: 'customer-ux',
    kind: 'module',
    phase: '4',
    label: 'Abandoned Cart Recovery',
    graphLabel: 'ABANDON CART',
    graphLabelShort: 'RECOVER',
    x: 18,
    y: 72,
    size: 'sm',
    purpose: 'Detects idle carts and sends recovery links via Resend.',
    inputs: ['Cart idle timestamp', 'User email', 'Cart line snapshot'],
    outputs: ['Recovery email', 'Deep-link cart restore', 'Conversion telemetry'],
    automationStatus: 'Fully Automated',
    implementationStatus: 'live',
    moduleKey: 'isAbandonedCartEnabled',
  },
  {
    id: 'auth',
    zone: 'core-engine',
    kind: 'platform',
    label: 'User Auth & Session',
    graphLabel: 'USER AUTH',
    x: 38,
    y: 26,
    purpose: 'Firebase Auth + server session cookies for checkout and account flows.',
    inputs: ['Email / password sign-in', 'Firebase ID token', 'Partner invite onboarding'],
    outputs: ['UID & session cookie', 'User profile document', 'Role & access level'],
    automationStatus: 'Fully Automated',
    implementationStatus: 'live',
    adminHref: '/admin/users',
    adminLinkLabel: 'Open User Management',
  },
  {
    id: 'kyb',
    zone: 'core-engine',
    kind: 'module',
    phase: '1',
    label: 'KYB Institution Verification',
    graphLabel: 'KYB VERIFY',
    x: 48,
    y: 18,
    purpose: 'Know-your-institution gate — W-9, EIN, lab docs; admin tier assignment.',
    inputs: ['Institution name & EIN', 'W-9 / lab letter upload', 'Authenticated UID'],
    outputs: ['institutionVerified flag', 'institutionTier assignment', 'Verification decision email'],
    automationStatus: 'Requires Admin Approval',
    implementationStatus: 'live',
    moduleKey: 'isInstitutionVerificationEnabled',
    requiresModuleKey: 'isB2BProcurementEnabled',
    adminHref: '/admin/verifications',
    adminLinkLabel: 'Open Verifications',
    storefrontHref: '/account/verify',
  },
  {
    id: 'pricing',
    zone: 'core-engine',
    kind: 'module',
    phase: '1',
    label: 'Algorithmic Tiered Pricing',
    graphLabel: 'TIER PRICING',
    x: 38,
    y: 44,
    purpose: 'Bronze, Silver, and Gold price lists override catalog retail for verified B2B accounts.',
    inputs: ['Cart SKU list', 'Catalog base prices', 'Institution tier from KYB'],
    outputs: ['Dynamic unit prices', 'Discount snapshot', 'Priced line-item payload'],
    automationStatus: 'Fully Automated',
    implementationStatus: 'live',
    moduleKey: 'isTieredPricingEnabled',
    requiresModuleKey: 'isB2BProcurementEnabled',
    adminHref: '/admin/products',
    adminLinkLabel: 'Open Tier Pricing',
  },
  {
    id: 'quotes',
    zone: 'core-engine',
    kind: 'module',
    phase: '1',
    label: 'Quote Workflow',
    graphLabel: 'QUOTES',
    x: 52,
    y: 32,
    size: 'sm',
    purpose: 'AE-generated quotes with PDF export for institutional procurement.',
    inputs: ['Priced cart lines', 'Institution profile', 'AE assignment'],
    outputs: ['Quote document', 'PDF export', 'Buyer checkout link', 'Net-terms eligibility signal'],
    automationStatus: 'Hybrid',
    implementationStatus: 'live',
    moduleKey: 'isQuoteWorkflowEnabled',
    requiresModuleKey: 'isB2BProcurementEnabled',
  },
  {
    id: 'checkout',
    zone: 'core-engine',
    kind: 'platform',
    label: 'Checkout Engine',
    graphLabel: 'CHECKOUT',
    x: 52,
    y: 44,
    size: 'lg',
    purpose: 'Validates stock, locks pricing, records RUO attestation, creates pending order, opens Stripe.',
    inputs: ['Priced cart lines', 'Session or guest email', 'Optional PO number'],
    outputs: ['Pending order document', 'stripeSessionId', 'Checkout redirect URL'],
    automationStatus: 'Fully Automated',
    implementationStatus: 'live',
    adminHref: '/admin/orders',
    adminLinkLabel: 'Open Orders',
    storefrontHref: '/checkout',
  },
  {
    id: 'fulfillment',
    zone: 'core-engine',
    kind: 'platform',
    label: 'Order Fulfillment Hub',
    graphLabel: 'FULFILLMENT',
    x: 58,
    y: 36,
    size: 'lg',
    purpose: 'Pick/pack hub between payment clearance and carrier shipping — inventory decrement and tracking.',
    inputs: ['Cleared funds signal', 'Paid order payload', 'Product stock levels'],
    outputs: ['Processing status', 'Carrier label request', 'Tracking metadata'],
    automationStatus: 'Hybrid',
    implementationStatus: 'live',
    adminHref: '/admin/inventory',
    adminLinkLabel: 'Open Inventory',
  },
  {
    id: 'orders',
    zone: 'core-engine',
    kind: 'platform',
    label: 'Order Lifecycle',
    graphLabel: 'ORDERS',
    x: 58,
    y: 52,
    purpose: 'Firestore order documents — pending through fulfilled with financial lock timestamps.',
    inputs: ['Checkout pending order', 'Stripe webhook settlement', 'Admin status PATCH'],
    outputs: ['Order status timeline', 'Financial lock fields', 'Fulfillment queue'],
    automationStatus: 'Hybrid',
    implementationStatus: 'live',
    adminHref: '/admin/orders',
    adminLinkLabel: 'Open Orders',
  },
  {
    id: 'inventory',
    zone: 'core-engine',
    kind: 'platform',
    label: 'Inventory & PO',
    graphLabel: 'INVENTORY',
    x: 48,
    y: 58,
    purpose: 'Stock levels, low-stock alerts, draft PO approve/export workflow.',
    inputs: ['Webhook stock decrement', 'Receiving updates', 'Low-stock thresholds'],
    outputs: ['Stock levels', 'Draft purchase orders', 'Reorder signals'],
    automationStatus: 'Hybrid',
    implementationStatus: 'live',
    adminHref: '/admin/inventory',
    adminLinkLabel: 'Open Inventory',
  },
  {
    id: 'loyalty',
    zone: 'core-engine',
    kind: 'module',
    phase: '4',
    label: 'Loyalty Ledger',
    graphLabel: 'LOYALTY',
    x: 38,
    y: 58,
    size: 'sm',
    purpose: 'Awards and redeems loyalty points — checkout redemption and citation research rewards.',
    inputs: ['Paid order total', 'Authenticated UID', 'Points balance', 'Research citation URL'],
    outputs: ['Points awarded', 'Tier progression', 'Redemption discount', 'Citation reward credits'],
    automationStatus: 'Fully Automated',
    implementationStatus: 'live',
    moduleKey: 'isLoyaltyRedemptionEnabled',
  },
  {
    id: 'modules',
    zone: 'core-engine',
    kind: 'platform',
    phase: '0',
    label: 'Module Control Center',
    graphLabel: 'MODULES',
    graphLabelShort: 'FLAGS',
    x: 42,
    y: 68,
    size: 'sm',
    purpose: 'Phase 0 feature-flag control plane for every V2 epic across Phases 1–5.',
    inputs: ['Super Admin PATCH', 'Firestore settings/modules', 'Default flag schema'],
    outputs: ['Module flag state', 'API route guards', 'UI feature visibility'],
    automationStatus: 'Requires Admin Approval',
    implementationStatus: 'live',
    adminHref: '/admin/modules',
    adminLinkLabel: 'Open Module Control',
  },
  {
    id: 'predictive-replenishment',
    zone: 'core-engine',
    kind: 'module',
    phase: '4',
    label: 'Predictive Replenishment',
    graphLabel: 'REPLENISH',
    graphLabelShort: 'RESTOCK',
    x: 52,
    y: 68,
    size: 'sm',
    purpose: '90-day velocity restock emails with 1-click cart rebuild.',
    inputs: ['Order velocity history', 'SKU consumption rate', 'User email'],
    outputs: ['Restock email', 'Pre-built cart link', 'Replenishment telemetry'],
    automationStatus: 'Fully Automated',
    implementationStatus: 'live',
    moduleKey: 'isPredictiveReplenishmentEnabled',
  },
  {
    id: 'stripe',
    zone: 'integrations',
    kind: 'integration',
    label: 'Stripe Payment Gateway',
    graphLabel: 'STRIPE',
    x: 78,
    y: 38,
    size: 'lg',
    purpose: 'Hosted payment collection and webhook settlement for cleared funds.',
    inputs: ['Checkout session total', 'Customer email', 'checkout.session.completed webhook', 'invoice.paid webhook'],
    outputs: ['Payment confirmation', 'stripePaymentIntentId', 'Cleared funds signal'],
    automationStatus: 'Fully Automated',
    implementationStatus: 'live',
    adminHref: '/admin/orders',
    adminLinkLabel: 'Open Orders',
    infrastructure: { provider: 'Stripe', envVars: ['STRIPE_SECRET_KEY', 'STRIPE_WEBHOOK_SECRET'] },
  },
  {
    id: 'stripe-tax',
    zone: 'integrations',
    kind: 'module',
    phase: '1',
    label: 'Stripe Tax',
    graphLabel: 'STRIPE TAX',
    graphLabelShort: 'TAX',
    x: 88,
    y: 26,
    size: 'sm',
    purpose: 'Automatic sales tax on Stripe Checkout sessions.',
    inputs: ['Shipping address', 'Line item tax codes', 'Institution tax-exempt flag'],
    outputs: ['Tax line items', 'Tax calculation ID', 'Compliance tax record'],
    automationStatus: 'Fully Automated',
    implementationStatus: 'live',
    moduleKey: 'isStripeTaxEnabled',
    infrastructure: { provider: 'Stripe', service: 'Tax' },
  },
  {
    id: 'net-terms',
    zone: 'integrations',
    kind: 'module',
    phase: '1',
    label: 'Net-30 Invoicing',
    graphLabel: 'NET TERMS',
    graphLabelShort: 'NET30',
    x: 88,
    y: 44,
    size: 'sm',
    purpose: 'Net-30 Stripe Invoices for verified institutional accounts.',
    inputs: ['Verified institution tier', 'Approved quote', 'Invoice line items'],
    outputs: ['Stripe Invoice', 'Payment terms record', 'Accounts receivable signal'],
    automationStatus: 'Hybrid',
    implementationStatus: 'live',
    moduleKey: 'isNetTermsEnabled',
    requiresModuleKey: 'isB2BProcurementEnabled',
    infrastructure: { provider: 'Stripe', service: 'Invoices' },
  },
  {
    id: 'resend',
    zone: 'integrations',
    kind: 'integration',
    label: 'Resend Email',
    graphLabel: 'RESEND',
    x: 88,
    y: 58,
    purpose: 'Transactional email — confirmations, verification, shipping, invites, cart recovery.',
    inputs: ['Webhook & admin triggers', 'Order / user context', 'RESEND API key'],
    outputs: ['Customer emails', 'Invite delivery', 'Delivery telemetry logs'],
    automationStatus: 'Fully Automated',
    implementationStatus: 'live',
    moduleKey: 'isTransactionalEmailEnabled',
    adminHref: '/admin/modules',
    adminLinkLabel: 'Open Modules',
    infrastructure: { provider: 'Resend', envVars: ['RESEND_API_KEY', 'RESEND_FROM_EMAIL'] },
  },
  {
    id: 'easypost',
    zone: 'integrations',
    kind: 'module',
    phase: '2',
    label: 'EasyPost Shipping',
    graphLabel: 'EASYPOST',
    graphLabelShort: 'SHIP',
    x: 78,
    y: 52,
    purpose: 'Carrier rates, labels, and tracking via EasyPost / ShipStation.',
    inputs: ['Fulfillment package dims', 'Origin / destination address', 'Carrier account'],
    outputs: ['Shipping label PDF', 'Tracking number', 'Carrier webhook events'],
    automationStatus: 'Fully Automated',
    implementationStatus: 'live',
    moduleKey: 'isRealShippingEnabled',
    infrastructure: { provider: 'EasyPost', service: 'Shipping API' },
  },
  {
    id: 'quickbooks',
    zone: 'integrations',
    kind: 'module',
    phase: '1',
    label: 'QuickBooks Export',
    graphLabel: 'QUICKBOOKS',
    graphLabelShort: 'QB',
    x: 78,
    y: 24,
    size: 'sm',
    purpose: 'Finance-ready CSV export of cleared orders for QuickBooks import.',
    inputs: ['Paid / fulfilled orders', 'Financial lock timestamp', 'Admin export request'],
    outputs: ['CSV ledger file', 'Audit log entry'],
    automationStatus: 'Hybrid',
    implementationStatus: 'live',
    moduleKey: 'isAccountingExportEnabled',
    adminHref: '/admin/orders',
    adminLinkLabel: 'Open Accounting Export',
    infrastructure: { provider: 'QuickBooks', service: 'CSV Import' },
  },
  {
    id: 'batch-coa',
    zone: 'compliance-ops',
    kind: 'module',
    phase: '2',
    label: 'Batch & COA Genealogy',
    graphLabel: 'BATCH COA',
    graphLabelShort: 'COA',
    x: 14,
    y: 90,
    size: 'sm',
    purpose: 'Immutable lot tracking with Storage COA PDFs and per-order batch assignment.',
    inputs: ['Receiving lot data', 'COA PDF upload', 'Order line SKU'],
    outputs: ['Batch genealogy record', 'COA download link', 'Lot assignment on order'],
    automationStatus: 'Hybrid',
    implementationStatus: 'live',
    moduleKey: 'isBatchCoaEnabled',
  },
  {
    id: 'geo-block',
    zone: 'compliance-ops',
    kind: 'module',
    phase: '2',
    label: 'Geo Restrictions',
    graphLabel: 'GEO BLOCK',
    graphLabelShort: 'GEO',
    x: 28,
    y: 92,
    size: 'sm',
    purpose: 'Blocks checkout from restricted states and regions.',
    inputs: ['Shipping state / region', 'Restricted region list', 'Checkout session'],
    outputs: ['Block decision', 'Compliance log entry', 'User-facing restriction message'],
    automationStatus: 'Fully Automated',
    implementationStatus: 'live',
    moduleKey: 'isComplianceGeoBlockEnabled',
  },
  {
    id: 'audit-logs',
    zone: 'compliance-ops',
    kind: 'platform',
    label: 'Compliance Audit Logs',
    graphLabel: 'AUDIT LOGS',
    graphLabelShort: 'AUDIT',
    x: 42,
    y: 90,
    size: 'sm',
    purpose: 'Audit trail for age gate, admin actions, CMS saves, and order mutations.',
    inputs: ['Admin API actions', 'Age gate events', 'Order mutations'],
    outputs: ['auditLogs documents', 'Compliance export', 'Forensic timeline'],
    automationStatus: 'Fully Automated',
    implementationStatus: 'live',
    adminHref: '/admin/audit',
    adminLinkLabel: 'Open Audit Logs',
  },
  {
    id: 'sales-command',
    zone: 'compliance-ops',
    kind: 'module',
    phase: '3',
    label: 'Sales Command Center',
    graphLabel: 'SALES CMD',
    graphLabelShort: 'SALES',
    x: 56,
    y: 92,
    size: 'sm',
    purpose: 'AE workspace for pipeline, institution accounts, and quote orchestration.',
    inputs: ['Lead assignments', 'Institution tier data', 'Quote requests'],
    outputs: ['AE dashboard metrics', 'Account ownership', 'Quote initiation'],
    automationStatus: 'Hybrid',
    implementationStatus: 'live',
    moduleKey: 'isSalesCommandCenterEnabled',
  },
  {
    id: 'client-impersonation',
    zone: 'compliance-ops',
    kind: 'module',
    phase: '3',
    label: 'Client Impersonation',
    graphLabel: 'IMPERSONATE',
    graphLabelShort: 'CO-BROWSE',
    x: 62,
    y: 88,
    size: 'sm',
    purpose: 'Secure AE co-browsing to build protocol carts for clients with audit trail.',
    inputs: ['AE authenticated session', 'Target client UID', 'Audit authorization'],
    outputs: ['Impersonated cart session', 'Audit log entry', 'Cart handoff to client'],
    automationStatus: 'Requires Admin Approval',
    implementationStatus: 'live',
    moduleKey: 'isClientImpersonationEnabled',
    requiresModuleKey: 'isSalesCommandCenterEnabled',
  },
  {
    id: 'lead-routing',
    zone: 'compliance-ops',
    kind: 'module',
    phase: '3',
    label: 'Lead Routing',
    graphLabel: 'LEAD ROUTE',
    graphLabelShort: 'LEADS',
    x: 34,
    y: 88,
    size: 'sm',
    purpose: 'Clearbit enrichment and AE assignment on researcher registration.',
    inputs: ['Signup email domain', 'Clearbit enrichment API', 'AE roster'],
    outputs: ['AE assignment', 'Lead score', 'CRM handoff signal'],
    automationStatus: 'Fully Automated',
    implementationStatus: 'live',
    moduleKey: 'isLeadRoutingEnabled',
    infrastructure: { provider: 'Clearbit', service: 'Enrichment API' },
  },
  {
    id: 'rbac',
    zone: 'compliance-ops',
    kind: 'module',
    phase: '3',
    label: 'Granular RBAC',
    graphLabel: 'RBAC',
    x: 70,
    y: 90,
    size: 'sm',
    purpose: 'Role-based access for ops, support, finance, and sales staff across admin routes.',
    inputs: ['User role document', 'Route permission matrix', 'Access level threshold'],
    outputs: ['Authorized route access', '403 guard signal', 'Role audit entry'],
    automationStatus: 'Fully Automated',
    implementationStatus: 'live',
    moduleKey: 'isGranularRbacEnabled',
    adminHref: '/admin/users',
    adminLinkLabel: 'Open User Management',
  },
  {
    id: 'margin-report',
    zone: 'compliance-ops',
    kind: 'module',
    phase: '3',
    label: 'Margin Reporting',
    graphLabel: 'MARGIN',
    graphLabelShort: 'MARGIN',
    x: 82,
    y: 90,
    size: 'sm',
    purpose: 'Gross margin dashboard using baseCost against realized order revenue.',
    inputs: ['Order revenue data', 'Product baseCost', 'Tier discount snapshot'],
    outputs: ['Margin dashboard', 'SKU profitability rank', 'Export CSV'],
    automationStatus: 'Hybrid',
    implementationStatus: 'live',
    moduleKey: 'isMarginReportingEnabled',
  },
];

export const SYSTEM_NODE_MAP = Object.fromEntries(
  SYSTEM_NODES.map((node) => [node.id, node])
) as Record<SystemNode['id'], SystemNode>;

export const DEFAULT_SYSTEM_NODE_ID: SystemNode['id'] = 'age-gate';

export const SYSTEM_NODE_RADIUS = 2.2;
export const SYSTEM_NODE_RADIUS_SM = 1.8;

export function nodeRadiusFor(node: SystemNode): number {
  if (node.size === 'sm') return SYSTEM_NODE_RADIUS_SM;
  if (node.size === 'lg') return SYSTEM_NODE_RADIUS + 0.6;
  return SYSTEM_NODE_RADIUS;
}

export const ZONE_LABELS: Record<SystemNode['zone'], string> = {
  infrastructure: 'Infrastructure & Code',
  'customer-ux': 'Customer UX & Storefront',
  'core-engine': 'Core Engine',
  integrations: 'Integrations & Ops',
  'compliance-ops': 'Compliance & Sales Command',
};
