import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { randomBytes } from 'node:crypto';
import { resolve } from 'node:path';

export type EnvPatch = {
  key: string;
  value?: string;
  generate?: () => string;
  /** Only set when the key is missing or empty */
  onlyIfMissing?: boolean;
  /** Merge comma-separated host lists */
  mergeCsv?: boolean;
};

function parseEnvLines(content: string): string[] {
  return content.split(/\r?\n/);
}

function getEnvValue(lines: string[], key: string): string | null {
  const prefix = `${key}=`;
  for (const line of lines) {
    if (line.startsWith(prefix)) {
      return line.slice(prefix.length);
    }
  }
  return null;
}

function setEnvValue(lines: string[], key: string, value: string): string[] {
  const prefix = `${key}=`;
  let found = false;
  const next = lines.map((line) => {
    if (line.startsWith(prefix)) {
      found = true;
      return `${prefix}${value}`;
    }
    return line;
  });
  if (!found) {
    if (next.length > 0 && next[next.length - 1] !== '') {
      next.push('');
    }
    next.push(`${prefix}${value}`);
  }
  return next;
}

function mergeCsvValues(existing: string | null, additions: string[]): string {
  const current = (existing ?? '')
    .split(',')
    .map((part) => part.trim())
    .filter(Boolean);
  const merged = new Set([...current, ...additions.map((part) => part.trim()).filter(Boolean)]);
  return [...merged].join(',');
}

export function patchEnvLocal(
  envPath: string,
  patches: EnvPatch[]
): { changed: string[]; path: string } {
  const resolved = resolve(envPath);
  const changed: string[] = [];
  let lines: string[];

  if (existsSync(resolved)) {
    lines = parseEnvLines(readFileSync(resolved, 'utf8'));
  } else {
    lines = ['# Generated by MedFit clinic dev setup'];
  }

  for (const patch of patches) {
    const current = getEnvValue(lines, patch.key);
    const isEmpty = current === null || current.trim() === '';

    if (patch.onlyIfMissing !== false && !isEmpty && !patch.mergeCsv) {
      continue;
    }

    let nextValue: string;
    if (patch.mergeCsv) {
      nextValue = mergeCsvValues(current, (patch.value ?? '').split(','));
      if (nextValue === (current ?? '').trim()) {
        continue;
      }
    } else {
      nextValue = patch.value ?? patch.generate?.() ?? '';
      if (!isEmpty && patch.onlyIfMissing !== false) {
        continue;
      }
    }

    lines = setEnvValue(lines, patch.key, nextValue);
    changed.push(patch.key);
  }

  if (changed.length > 0) {
    const content = lines.join('\n').replace(/\n*$/, '\n');
    writeFileSync(resolved, content, 'utf8');
  }

  return { changed, path: resolved };
}

export function generateCronSecret(): string {
  return randomBytes(32).toString('hex');
}
