'use client';

import React, { useEffect, useState } from 'react';
import { db } from '../../lib/firebase/firestore';
import { collection, query, orderBy, onSnapshot } from 'firebase/firestore';
import type { PurchaseOrder } from '../../lib/types';

/**
 * Displays pending Purchase Orders generated by the system.
 */
export const POList = () => {
  const [pos, setPos] = useState<PurchaseOrder[]>([]);

  useEffect(() => {
    const q = query(collection(db, 'purchaseOrders'), orderBy('generatedAt', 'desc'));
    const unsubscribe = onSnapshot(q, (snapshot) => {
      setPos(snapshot.docs.map((doc) => ({ id: doc.id, ...doc.data() } as PurchaseOrder)));
    });
    return () => unsubscribe();
  }, []);

  return (
    <div className="space-y-4">
      <h2 className="text-xl font-bold mb-4">Pending Purchase Orders</h2>
      {pos.length === 0 && <p className="text-gray-500">No pending POs found.</p>}
      {pos.map((po) => (
        <div
          key={po.id}
          className="bg-white/5 p-6 rounded-xl border border-white/10 flex justify-between items-center"
        >
          <div>
            <h3 className="font-bold">{po.supplierId}</h3>
            <p className="text-sm text-gray-400">
              Created:{' '}
              {po.generatedAt?.toDate
                ? po.generatedAt.toDate().toLocaleDateString()
                : 'Recently'}
            </p>
            <p className="text-sm text-gray-500">{po.items?.length ?? 0} item(s)</p>
          </div>
          <span className="text-orange-400 font-mono text-sm">{po.status}</span>
        </div>
      ))}
    </div>
  );
};
